name: Verify Terraform Files

on:
  push:
    branches:
      - 'dev-*'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Verify Terraform Files
        run: |
          required_files=("main.tf" "variables.tf" "outputs.tf" "provider.tf" "terraform.tfvars" "versions.tf" "data.tf" "backend.tf")
          missing=()
          for f in "${required_files[@]}"; do
            if [ ! -f "$f" ]; then
              missing+=("$f")
            fi
          done
          if [ ${#missing[@]} -ne 0 ]; then
            echo "❌ Missing files: ${missing[*]}"
            exit 1
          fi
          echo "✅ All required Terraform files are present."
